config/routes.rb
Rails.application.routes.draw do

  resources :responses
  resources :tests
  resources :plans
  root to: "pages#home"

  resources   :pages
  devise_for  :users

end

app/models/plan.rb
class Plan < ActiveRecord::Base
end

app/models/response.rb
class Response < ActiveRecord::Base
  belongs_to :test
end

app/models/test.rb
class Test < ActiveRecord::Base
  has_many :responses
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

end

app/controllers/plans_controller.rb
class PlansController < InheritedResources::Base

  private

    def plan_params
      params.require(:plan).permit(:title, :description)
    end
end

app/controllers/responses_controller.rb
class ResponsesController < InheritedResources::Base

  def create
    @response = Response.new(response_params)

    respond_to do |format|
      if @response.save
        format.html { redirect_to response_path(@response) }
      else
        format.html { render :new }
        format.json { render json: @response.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def response_params
      params.require(:response).permit(:test_id, :name, :answer)
    end
end

app/controllers/tests_controller.rb
class TestsController < InheritedResources::Base

  before_action :set_test, only: [:show, :edit, :update, :destroy]

  def show
    @responses = @test.responses
    @opt1_res = @responses.where(answer: "A")
    @opt2_res = @responses.where(answer: "B")
    @opt3_res = @responses.where(answer: "C")
    @opt4_res = @responses.where(answer: "D")
    @opt1_count = @opt1_res.count
    @opt2_count = @opt2_res.count
    @opt3_count = @opt3_res.count
    @opt4_count = @opt4_res.count
  end

  private

    def set_test
      @test = Test.find(params[:id])
    end

    def test_params
      params.require(:test).permit(:question, :opt1_type, :opt1_words, :opt2_type, :opt2_words, :opt3_type, :opt3_words, :opt4_type, :opt4_words, :answer, :question_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
        concat(content_tag(:div, message, class: "container") do
          concat message
        end)
      end)
    end
    nil
  end

end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lessonbase</title>
  <!-- Viewport -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- FontAwesome -->
  <script defer src="https://pro.fontawesome.com/releases/v5.0.8/js/solid.js" integrity="sha384-jTxqWCb7UqRDQDd2Nkuh5BkHe9k+ElbFLa3NaJfid5kBK/+cVktzVRXrw0isFWxf" crossorigin="anonymous"></script>
  <script defer src="https://pro.fontawesome.com/releases/v5.0.8/js/fontawesome.js" integrity="sha384-Ht3fAeBiX/rVmKVyMwONAIIt0aRoPzZgq1FzdRgR9zFo+Kcd8YDwUbFlTItfaYW4" crossorigin="anonymous"></script>
</head>
<body>
  <%= flash_messages %>
  <div class="container">
    <%= yield %>
  </div>  
</body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 success">
      <h1>Welcome to<br>Lessonbase</h1>
      <%= link_to "New Test", new_test_path, class: "btn btn-lg btn-outline-dark" %><br>
      <%= link_to "New Response", new_response_path, class: "btn btn-lg btn-outline-dark" %>
    </div>
  </div>
</div>

app/views/plans/_form.html.erb
<%= form_for(@plan) do |f| %>
  <% if @plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
      <% @plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plans/edit.html.erb
<h1>Editing Plan</h1>

<%= render 'form' %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Plans</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plans.each do |plan| %>
      <tr>
        <td><%= plan.title %></td>
        <td><%= plan.description %></td>
        <td><%= link_to 'Show', plan %></td>
        <td><%= link_to 'Edit', edit_plan_path(plan) %></td>
        <td><%= link_to 'Destroy', plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plan', new_plan_path %>

app/views/plans/new.html.erb
<h1>New Plan</h1>

<%= render 'form' %>

<%= link_to 'Back', plans_path %>

app/views/plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @plan.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @plan.description %>
</p>

<%= link_to 'Edit', edit_plan_path(@plan) %> |
<%= link_to 'Back', plans_path %>

app/views/responses/_form.html.erb
<%= form_for(@response) do |f| %>

<div id="responseForm">
  <div class="row">
    <div class="col-lg-12">
      <div class="form-group">
        <%= f.text_field :test_id, placeholder: "Test Number", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.text_field :name, placeholder: "Name", class: "form-control" %>
      </div>
      <%= f.hidden_field :answer %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-3 col-md-6 col-6">
      <a class="btn btn-lg btn-answer" id="answerA">A</a>
    </div>
    <div class="col-lg-3 col-md-6 col-6">
      <a class="btn btn-lg btn-answer" id="answerB">B</a>
    </div>
    <div class="col-lg-3 col-md-6 col-6">
      <a class="btn btn-lg btn-answer" id="answerC">C</a>
    </div>
    <div class="col-lg-3 col-md-6 col-6">
      <a class="btn btn-lg btn-answer" id="answerD">D</a>
    </div>
  </div>
</div>

<% end %>

<script type="text/javascript">
  $('#answerA').click(function() {
    $('#response_answer').val('A');
    $('form').submit();
  });
  $('#answerB').click(function() {
    $('#response_answer').val('B');
    $('form').submit();
  });
  $('#answerC').click(function() {
    $('#response_answer').val('C');
    $('form').submit();
  });
  $('#answerD').click(function() {
    $('#response_answer').val('D');
    $('form').submit();
  });
</script>

app/views/responses/edit.html.erb
<h1>Editing Response</h1>

<%= render 'form' %>

<%= link_to 'Show', @response %> |
<%= link_to 'Back', responses_path %>

app/views/responses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Responses</h1>

<table>
  <thead>
    <tr>
      <th>Test</th>
      <th>Name</th>
      <th>Answer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @responses.each do |response| %>
      <tr>
        <td><%= response.test.id %></td>
        <td><%= response.name %></td>
        <td><%= response.answer %></td>
        <td><%= link_to 'Show', response %></td>
        <td><%= link_to 'Edit', edit_response_path(response) %></td>
        <td><%= link_to 'Destroy', response, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Response', new_response_path %>

app/views/responses/new.html.erb
<div class="container">
  <%= render 'form' %>
</div>

app/views/responses/show.html.erb
<div class="success">
  <h1>Thank you!</h1>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>